/* =========================================================
   CUSTOMERS
   ========================================================= */
CREATE TABLE Customers (
    CustomerID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName   VARCHAR2(50)  NOT NULL,
    LastName    VARCHAR2(50)  NOT NULL,
    Country     VARCHAR2(60)  NOT NULL,
    Score       NUMBER(3)     NULL,
    CONSTRAINT CK_Customers_Score CHECK (Score BETWEEN 0 AND 100)
);
-- CUSTOMERS
INSERT INTO Customers (CustomerID, FirstName, LastName, Country, Score) VALUES (201, 'Ava',   'Martin',  'USA',    82);
INSERT INTO Customers (CustomerID, FirstName, LastName, Country, Score) VALUES (202, 'Liam',  'Nguyen',  'Canada', 76);
INSERT INTO Customers (CustomerID, FirstName, LastName, Country, Score) VALUES (203, 'Sofia', 'Khan',    'UK',     91);
INSERT INTO Customers (CustomerID, FirstName, LastName, Country, Score) VALUES (204, 'Ethan', 'Silva',   'Brazil', 68);
INSERT INTO Customers (CustomerID, FirstName, LastName, Country, Score) VALUES (205, 'Mia',   'Rossi',   'Italy',  73);
INSERT INTO Customers (CustomerID, FirstName, LastName, Country, Score) VALUES (206, 'Noah',  'Yamada',  'Japan',  88);
INSERT INTO Customers (CustomerID, FirstName, LastName, Country, Score) VALUES (207, 'Emma',  'Dubois',  'France', 80);
INSERT INTO Customers (CustomerID, FirstName, LastName, Country, Score) VALUES (208, 'Lucas', 'Schmidt', 'Germany',79);
