/* =========================================================
   ORDERS
   ========================================================= */
CREATE TABLE Orders (
    OrderID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductID     NUMBER NOT NULL,
    CustomerID    NUMBER NOT NULL,
    SalesPersonID NUMBER NOT NULL,
    OrderDate     DATE NOT NULL,
    ShipDate      DATE NULL,
    OrderStatus   VARCHAR2(20) NOT NULL,
    ShipAddress   VARCHAR2(200) NOT NULL,
    BillAddress   VARCHAR2(200) NOT NULL,
    Quantity      NUMBER NOT NULL,
    Sales         NUMBER(12,2) NOT NULL,
    CreationTime  TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_Orders_Quantity CHECK (Quantity > 0),
    CONSTRAINT CK_Orders_Sales    CHECK (Sales >= 0),
    CONSTRAINT CK_Orders_Status   CHECK (OrderStatus IN ('Pending','Shipped','Cancelled')),
    CONSTRAINT FK_Orders_Product   FOREIGN KEY (ProductID)     REFERENCES Products(ProductID),
    CONSTRAINT FK_Orders_Customer  FOREIGN KEY (CustomerID)    REFERENCES Customers(CustomerID),
    CONSTRAINT FK_Orders_Employee  FOREIGN KEY (SalesPersonID) REFERENCES Employees(EmployeeID)
);
-- ORDERS
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (401, 101, 201, 302, DATE '2025-11-05', DATE '2025-11-08', 'Shipped', '123 Main St, Austin, TX',    '123 Main St, Austin, TX',     2,  2998.00, TIMESTAMP '2025-11-05 09:32:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (402, 103, 202, 303, DATE '2025-11-12', DATE '2025-11-14', 'Shipped', '55 King St, Toronto, ON',    '55 King St, Toronto, ON',     3,    89.97, TIMESTAMP '2025-11-12 14:10:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (403, 105, 203, 304, DATE '2025-11-20', DATE '2025-11-24', 'Shipped', '7 Baker St, London, UK',     '7 Baker St, London, UK',      1,   329.00, TIMESTAMP '2025-11-20 10:45:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (404, 108, 201, 302, DATE '2025-11-25', DATE '2025-11-28', 'Shipped', '123 Main St, Austin, TX',    '123 Main St, Austin, TX',     2,   238.00, TIMESTAMP '2025-11-25 16:20:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (405, 109, 204, 305, DATE '2025-12-01', DATE '2025-12-06', 'Shipped', '400 Av. Paulista, São Paulo', '400 Av. Paulista, São Paulo',  1,   249.00, TIMESTAMP '2025-12-01 09:00:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (406, 104, 205, 304, DATE '2025-12-03', DATE '2025-12-05', 'Shipped', 'Via Roma 10, Milan, Italy',  'Via Roma 10, Milan, Italy',   2,   179.98, TIMESTAMP '2025-12-03 11:25:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (407, 106, 206, 303, DATE '2025-12-08', DATE '2025-12-11', 'Shipped', '1-2-3 Shibuya, Tokyo, Japan','1-2-3 Shibuya, Tokyo, Japan', 3,   149.97, TIMESTAMP '2025-12-08 13:40:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (408, 107, 207, 305, DATE '2025-12-10', NULL,               'Pending',  '22 Rue Victor, Paris, FR',   '22 Rue Victor, Paris, FR',    1,   129.00, TIMESTAMP '2025-12-10 10:05:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (409, 110, 208, 302, DATE '2025-12-12', NULL,               'Pending',  '8 Marktstr, Berlin, DE',     '8 Marktstr, Berlin, DE',      2,   118.00, TIMESTAMP '2025-12-12 15:18:00');
INSERT INTO Orders (OrderID, ProductID, CustomerID, SalesPersonID, OrderDate, ShipDate, OrderStatus, ShipAddress, BillAddress, Quantity, Sales, CreationTime) VALUES (410, 102, 203, 304, DATE '2025-12-15', NULL,               'Cancelled','7 Baker St, London, UK',     '7 Baker St, London, UK',      1,  1099.00, TIMESTAMP '2025-12-15 09:55:00');
