/

/* =========================================================
   PRODUCTS
   ========================================================= */
CREATE TABLE Products (
    ProductID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Product     VARCHAR2(100) NOT NULL,
    Category    VARCHAR2(50)  NOT NULL,
    Price       NUMBER(10,2)  NOT NULL,
    CONSTRAINT CK_Products_Price CHECK (Price >= 0)
);
/* =========================================================
   Seed Data
   ========================================================= */
-- PRODUCTS
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (101, 'Laptop Pro 14',       'Electronics', 1499.00);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (102, 'Laptop Air 13',       'Electronics', 1099.00);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (103, 'Wireless Mouse',      'Accessories',   29.99);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (104, 'Mechanical Keyboard', 'Accessories',   89.99);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (105, '27"" 4K Monitor',     'Electronics',  329.00);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (106, 'USB-C Hub 7-in-1',    'Accessories',   49.99);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (107, 'Noise-Cancel Headset','Accessories',  129.00);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (108, 'External SSD 1TB',    'Storage',      119.00);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (109, 'Office Chair Ergonomic','Furniture',  249.00);
INSERT INTO Products (ProductID, Product, Category, Price) VALUES (110, 'Webcam 1080p',        'Accessories',   59.00);
